from tkinter import *
import calendar
root=Tk()
root.geometry('330x340')
root.resizable(0,0)
root.configure(background='pink')
root.title('Calender')
def show():
    a = int(spin1.get())
    b = int(spin2.get())
    #print(calendar.month(b,a))
    cal=calendar.month(b,a)
    txt.delete(0.0,END)
    txt.insert(INSERT,cal)
photo=PhotoImage(file='aa.png')
bt2=Button(root,image=photo).pack()
lbl1 = Label(root,text='Month',font=('Arial bold',17)).place(x=15,y=5)
lbl2 = Label(root,text="Year",font=('Arial bold',17)).place(x=175,y=5)
spin1 = Spinbox(root,values=(1,2,3,4,5,6,7,8,9,10,11,12),width=3,font=('Helvetica',17,'bold'))
spin1.place(x=90,y=5)
spin2 = Spinbox(root,from_=1800,to_=2100,width=4,font=('Helvetica',17,'bold'))
spin2.place(x=230,y=5)
btn = Button(root,text='Show',font=('Arial',15),borderwidth=6,command=show).place(x=130,y=47)
txt = Text(root,width=30,height=12,fg='black')
txt.place(x=40,y=100)
root.mainloop()